# Generated by Django 3.1.3 on 2022-03-16 12:12

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='College',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('college_name', models.CharField(max_length=255, unique=True)),
                ('college_identifier', models.CharField(max_length=10, unique=True)),
                ('college_email', models.EmailField(blank=True, max_length=255, null=True)),
                ('college_number', models.IntegerField(blank=True, null=True)),
                ('college_website', models.CharField(blank=True, max_length=255, null=True)),
                ('college_description', models.TextField(blank=True, null=True)),
                ('college_vision', models.TextField(blank=True, null=True)),
                ('college_mission', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Faculty',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('faculty_identifier', models.CharField(max_length=255, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Society',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('society_name', models.CharField(max_length=255)),
                ('society_identifier', models.CharField(max_length=255, unique=True)),
                ('society_email', models.EmailField(blank=True, max_length=255, null=True)),
                ('society_number', models.IntegerField(blank=True, null=True)),
                ('society_website', models.CharField(blank=True, max_length=255, null=True)),
                ('society_description', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('student_identifier', models.CharField(max_length=255, unique=True)),
                ('student_societies', models.ManyToManyField(blank=True, related_name='student_societies', to='database_main.Society')),
            ],
        ),
    ]
